name: CI/CD for Tomcat (Windows)
on:
  push:
    branches:
      - main  # Trigger this workflow on push to the main branch
jobs:
  build:
    runs-on: windows-latest  # Use the latest Windows runner
    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
    # Step 2: Set up Java environment
    - name: Set up Java 23
      uses: actions/setup-java@v3
      with:
        java-version: '23'  # Set the Java version to 11 (adjust if needed)
    # Step 3: Build the project using Maven (or any build tool you're using)
    - name: Build with Maven
      run: mvn clean package
  deploy:
    needs: build  # This job will run after the build job
    runs-on: windows-latest
    steps:
    # Step 1: Copy the WAR file to the Tomcat server
    - name: Deploy to Tomcat
      uses: appleboy/ssh-action@v0.1.5  # SSH action to deploy the WAR file
      with:
        host: ${{ secrets."192.168.1.101" }}   # Tomcat server IP address
        username: ${{ secrets.admin }} # SSH username
        password: ${{ secrets.admin }} # SSH password
        source: target/*.war               # Path to the WAR file generated by Maven
        target: C:\Program Files (x86)\Java\jre1.8.0_431\Server1\webapps  # Target directory on the Tomcat server (adjust the path)
